app = "stream-closed-captioner"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "/app/bin/stream_closed_captioner_phoenix eval \"StreamClosedCaptionerPhoenix.Release.migrate\""

[env]
  PORT = "4000"
  MIX_ENV = "prod"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

[[vm]]
  memory = "4gb"
  cpu_kind = "shared"
  cpus = 2
