import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :stream_closed_captioner_phoenix, StreamClosedCaptionerPhoenixWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :stream_closed_captioner_phoenix, StreamClosedCaptionerPhoenixWeb.Endpoint,
  # Some proxies (notably some Coolify/Traefik setups) forward the original
  # scheme as X-Forwarded-Scheme rather than X-Forwarded-Proto. Trust both so
  # Plug.SSL doesn't 301-redirect WebSocket upgrades behind such proxies.
  force_ssl: [rewrite_on: [:x_forwarded_proto, :x_forwarded_scheme]]
